[package]
name = "porter-audio"
version = "0.1.0"
edition = "2024"

[dependencies]
porter-utils = { path = "../porter-utils" }
porter-macros = { path = "../porter-macros" }

claxon.workspace = true
flacenc.workspace = true
miniserde.workspace = true
lewton = { workspace = true, optional = true }

[features]
# Enables reading ms adpcm wav files.
ms-adpcm = []
# Enables reading wwise vorbis wem files.
wwise-vorbis = ["dep:lewton"]
# Enabled reading headerless flac files.
raw-flac = []
# Enables reading ogg files.
ogg = ["dep:lewton", "lewton/ogg"]
# Enables extra debug logging.
debug = []
# Removes 'DTZxPorter' branding.
debrand = []
